

### Nombre: Juan Pablo Jaramillo Castrillon.
### De: Colombia - Rionegro (Antiquia)
### Nació: 11 de Mayo de 1996.





##Perfil:

Estudiante de octavo semestre de Estadística. Se caracteriza por su disciplina, dedicación, proactividad, imaginación e iniciativa para desarrollar nuevas ideas. Dispuesto a crecer continuamente, abierto al cambio, versátil para adaptarse a diferentes ambientes laborales y con facilidad para trabajar bajo presión. Sus áreas de interés son relacionadas con estadística, lenguajes de programación, innovación y optimización de procesos.

## Formación Academica:


### Universitarios:
  * Estadística – Octavo Semestre
  Universidad Nacional De Colombia, Medellín.
  
### Secundarios:

*	Colegio San Antonio de Pereira, Rionegro, Antioquia
	Bachiller, 2013.


### Estudios Complementarios

* Asistente al Simposio Internacional de Estadística 
Versión XXVII (Medellin)



* Ponente al Simposio internacional de Estadística versión XXIX. (Barranquilla) Con “Una aplicación de modelos jerárquicos con Splines Cúbicos en Galmss”


### Habilidades informáticas: 

•	Dominio total de la suite Microsoft Office
•	R (Alto)
•	Latex (Alto)
•	Python (Medio)
•	SQL. (Medio)

